version: "3"

services:

  web:
    build: .
    image: crypto-dashboard-web
    restart: always
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    container_name: crypto-dashboard-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web