name: CI CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SV_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            if [ ! -d "/var/www/app/.git" ]; then
              git clone https://github.com/luuson/test-cicd.git /var/www/app
            else
              cd /var/www/app
              git pull origin main
            fi