name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SV_IP }}
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            set -e

            cd /home/ec2-user

            if [ ! -d "crypto-dashboard" ]; then
              echo "Cloning repo..."
              git clone https://github.com/luuson/test-cicd.git crypto-dashboard
            fi

            cd crypto-dashboard

            echo "Pull latest code..."
            git pull --ff-only origin main

            echo "Deploy Docker..."
            sudo docker compose down
            sudo docker compose pull
            sudo docker compose up -d --build --remove-orphans

            echo "Done!"